# Site settings
email: karelz@microsoft.com
description: > #
url: "https://karelz.github.io"
github_username:  karelz
twitter_username: ziki_cz

permalink: /:categories/:year/:month/:day/:title/
contenturl: "/blog/content/"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  #parse_span_html: true
excerpt_separator: <!--more-->

disqus: karelz

google_analytics_ua: UA-101625295-1

#paginate: 5

exclude:
  - LICENSE
  - README.md
